# Generated by Django 3.2.8 on 2021-11-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lidlguru", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(to="lidlguru.Category"),
        ),
    ]
